name: zimbapos
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  go_router: ^13.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.2
  uuid: ^4.2.2
  flutter_easyloading: ^3.0.5
  responsive_sizer: ^3.2.0
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_animate: ^4.4.0
  server:
    path: ./packages/server
  intl: ^0.19.0
  validators: ^3.0.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  network_info_plus: ^4.1.0
  dart_jsonwebtoken: ^2.12.2
  flutter_dotenv: ^5.1.0
  form_validator: ^2.1.1
  platform_device_id: ^1.0.1
  device_info_plus: ^9.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  rename: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/zimba_pos_img.png
    - assets/fonts/
    - production.env

  fonts:
    - family: PJS
      fonts:
        - asset: assets/fonts/PlusJakartaSans_Bold.ttf
        - asset: assets/fonts/PlusJakartaSans_Medium.ttf
        - asset: assets/fonts/PlusJakartaSans_SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans_Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
