name: zimbapos
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  go_router: ^13.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.2
  uuid: ^4.2.2
  flutter_easyloading: ^3.0.5
  responsive_sizer: ^3.2.0
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_animate: ^4.4.0
  server:
    path: ./packages/server
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/zimba_pos_img.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
