// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTIAmFj5rjtBJ40wMqHcPN-Si-cqX_pU',
    appId: '1:665566285485:web:9c185b74734e218f1e4024',
    messagingSenderId: '665566285485',
    projectId: 'zimbapos-7cf35',
    authDomain: 'zimbapos-7cf35.firebaseapp.com',
    storageBucket: 'zimbapos-7cf35.appspot.com',
    measurementId: 'G-ZWHX3Z2QQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxbcrJ4_K6pO2L10wRiHDb0LvKo-vUps',
    appId: '1:665566285485:android:f7641a8a62c778b01e4024',
    messagingSenderId: '665566285485',
    projectId: 'zimbapos-7cf35',
    storageBucket: 'zimbapos-7cf35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIy2MnBVKGoLKZrS8zHSV-ueSIGSm19s',
    appId: '1:665566285485:ios:548ffe76cc0622ee1e4024',
    messagingSenderId: '665566285485',
    projectId: 'zimbapos-7cf35',
    storageBucket: 'zimbapos-7cf35.appspot.com',
    iosBundleId: 'com.codanto.zimbaposApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZIy2MnBVKGoLKZrS8zHSV-ueSIGSm19s',
    appId: '1:665566285485:ios:751f8faf9f0d79471e4024',
    messagingSenderId: '665566285485',
    projectId: 'zimbapos-7cf35',
    storageBucket: 'zimbapos-7cf35.appspot.com',
    iosBundleId: 'com.example.zimbapos.RunnerTests',
  );
}
